proto < ../proto/depot.proto
### SellShares
GRPC raynkami-balance-server.sliplane.app:50051/Depot/SellShares
{
    "count": 1, 
    "price_per_share": 2.0, 
    "symbol": "AAPL"
}
###

GRPC raynkami-balance-server.sliplane.app:50051/Depot/BuyShares
{"count": 1, "price_per_share": 2.0, "symbol": "AAPL"}
###

GRPC raynkami-balance-server.sliplane.app:50051/Depot/Withdraw
{"amount": 100.0}
###

GRPC raynkami-balance-server.sliplane.app:50051/Depot/Deposit
{"amount": 100.0}
###

GRPC raynkami-balance-server.sliplane.app:50051/Depot/GetState
{}
###

GRPC raynkami-balance-server.sliplane.app:50051/Depot/GetGain
{}
###

GRPC raynkami-balance-server.sliplane.app:50051/Depot/GetShareBalance
{"symbol": "ORCL"}